version: "3.8"

services:
  postgres:
    imagen: postgres
    restart: always
    ports:
      - "5432:5432"
    enviroment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ilaze-db

  pgAdmin:
    image: dpage/pgadmin4
    enviroment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres
